language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9-multilib
      - g++-4.9-multilib
env:
  - CC=gcc-4.9
  - CXX=g++-4.9
script:
  - cmake .
  - make
