version: '{build}'
image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
clone_folder: c:\projects\FCNPC

configuration:
  - RelWithDebInfo

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake ..

build:
  project: c:\projects\FCNPC\build\FCNPC.sln
  verbosity: minimal
  parallel: true

artifacts:
  - path: FCNPC*.dll
    name: Binary package
